version: '2'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=yago
      - RABBITMQ_DEFAULT_PASS=testeteste
    ports:
      - "5672:5672"
      - "25676:25676"
      - "15672:15672"

  worker:
    hostname: celery
    build:
      context: ./robo
      dockerfile: Dockerfile
    environment:
      - CELERY_URI=amqp://yago:testeteste@rabbit:5672
      - CELERY_NAME=hello
    links:
      - rabbit
    depends_on:
      - rabbit

  api:
    hostname: tornado
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - CELERY_URI=amqp://yago:testeteste@rabbit:5672
    ports:
      - "8081:8888"
    links:
      - rabbit
      - worker
    depends_on:
      - rabbit