version: '2'
services:
	rabbit:
		hostname: rabbit
		image: rabbitmq:latest
		environment:
			- RABBITMQ_DEFAULT_USER=guest
			- RABBITMQ_DEFAULT_PASS=guest
		ports:
			- "5672:5672"
			- "25676:25676"
			- "8080:15672"

	worker:
		build:
			context: ./robo
			dockerfile: dockerfile
		volumes:
			- .:/app
		links:
			- rabbit
		depends_on:
			- rabbit